ln -s $(which ccache) asdk64-linux-addr2line
ln -s $(which ccache) asdk64-linux-ar
ln -s $(which ccache) asdk64-linux-as
ln -s $(which ccache) asdk64-linux-c++
ln -s $(which ccache) asdk64-linux-c++filt
ln -s $(which ccache) asdk64-linux-config
ln -s $(which ccache) asdk64-linux-cpp
ln -s $(which ccache) asdk64-linux-dwp
ln -s $(which ccache) asdk64-linux-elfedit
ln -s $(which ccache) asdk64-linux-g++
ln -s $(which ccache) asdk64-linux-gcc
ln -s $(which ccache) asdk64-linux-gcc-5.4.1
ln -s $(which ccache) asdk64-linux-gcc-ar
ln -s $(which ccache) asdk64-linux-gcc-nm
ln -s $(which ccache) asdk64-linux-gcc-ranlib
ln -s $(which ccache) asdk64-linux-gcov
ln -s $(which ccache) asdk64-linux-gcov-tool
ln -s $(which ccache) asdk64-linux-gdb
ln -s $(which ccache) asdk64-linux-gprof
ln -s $(which ccache) asdk64-linux-ld
ln -s $(which ccache) asdk64-linux-ld.bfd
ln -s $(which ccache) asdk64-linux-ld.gold
ln -s $(which ccache) asdk64-linux-lstrip
ln -s $(which ccache) asdk64-linux-mklink
ln -s $(which ccache) asdk64-linux-nm
ln -s $(which ccache) asdk64-linux-objcopy
ln -s $(which ccache) asdk64-linux-objdump
ln -s $(which ccache) asdk64-linux-ranlib
ln -s $(which ccache) asdk64-linux-readelf
ln -s $(which ccache) asdk64-linux-relink
ln -s $(which ccache) asdk64-linux-size
ln -s $(which ccache) asdk64-linux-sstrip
ln -s $(which ccache) asdk64-linux-strings
ln -s $(which ccache) asdk64-linux-strip
ln -s $(which ccache) asdk64-linux-wrapper
