ln -s $(which ccache) msdk-linux-addr2line
ln -s $(which ccache) msdk-linux-ar
ln -s $(which ccache) msdk-linux-as
ln -s $(which ccache) msdk-linux-c++
ln -s $(which ccache) msdk-linux-c++filt
ln -s $(which ccache) msdk-linux-config
ln -s $(which ccache) msdk-linux-cpp
ln -s $(which ccache) msdk-linux-elfedit
ln -s $(which ccache) msdk-linux-g++
ln -s $(which ccache) msdk-linux-gcc
ln -s $(which ccache) msdk-linux-gcc-4.8.5
ln -s $(which ccache) msdk-linux-gcc-ar
ln -s $(which ccache) msdk-linux-gcc-nm
ln -s $(which ccache) msdk-linux-gcc-ranlib
ln -s $(which ccache) msdk-linux-gcov
ln -s $(which ccache) msdk-linux-gdb
ln -s $(which ccache) msdk-linux-gprof
ln -s $(which ccache) msdk-linux-ld
ln -s $(which ccache) msdk-linux-ld.bfd
ln -s $(which ccache) msdk-linux-lstrip
ln -s $(which ccache) msdk-linux-mklink
ln -s $(which ccache) msdk-linux-nm
ln -s $(which ccache) msdk-linux-objcopy
ln -s $(which ccache) msdk-linux-objdump
ln -s $(which ccache) msdk-linux-ranlib
ln -s $(which ccache) msdk-linux-readelf
ln -s $(which ccache) msdk-linux-relink
ln -s $(which ccache) msdk-linux-run
ln -s $(which ccache) msdk-linux-size
ln -s $(which ccache) msdk-linux-sstrip
ln -s $(which ccache) msdk-linux-strings
ln -s $(which ccache) msdk-linux-strip
ln -s $(which ccache) msdk-linux-wrapper
